Minimal proposal spec
ajvincent/proposal-mass-proxy-revocation pull request #12
Opened 2022-04-07 08:35 UTC by Jack-Works

close #8 

![image](https://user-images.githubusercontent.com/5390719/162156980-f09d4a44-cbde-49ba-b2e4-7d98bf7ae2b5.png)

![image](https://user-images.githubusercontent.com/5390719/162157005-ccd5827e-034b-4b24-acc8-66921f2f3f53.png)

![image](https://user-images.githubusercontent.com/5390719/162157029-31350c7e-cb6f-4fb2-9a08-28c969d1ae30.png)

![image](https://user-images.githubusercontent.com/5390719/162157050-40bfdb7d-d2dc-4b55-859d-f3c69a0dbd86.png)

2022-04-07 10:49 UTC, acutmore commented
Only having the `isRevoked` getter and not a way to _listen_ for the revoke call seems like it would add a delay to when the `target` and `handler` references are dropped allowing them to be collected?

2022-04-07 15:05 UTC, ajvincent commented
I think having `Proxy.revocable()` **not** always return `{proxy, revoke}` is something we can not ask for.  Though it may seem weird, I can foresee someone out there wanting to still revoke an individual proxy, while letting hundreds of others live.  Plus, it's a change in what the function actually returns from a generic dictionary to a Proxy.

So the algorithm at 1.3 step 3b has to go, and the "Else" branch at 1.4 has to be unconditionally run, I think.

2022-04-07 15:07 UTC, ajvincent requested changes
I don't think we can change the return signature of Proxy.revocable.

2022-04-08 03:16 UTC, Jack-Works commented
The current semantics allows the engine to GC all targets & handlers of the proxy.

> I think having Proxy.revocable() not always return {proxy, revoke} is something we can not ask for.

What about changing `Proxy.revocable` to return `{ proxy: T, revoke?: Function }`? I prefer adding this functionality to the `Proxy.revocable` instead of `new Proxy` because it has better semantics.

2022-04-08 03:17 UTC, Jack-Works commented
> Though it may seem weird, I can foresee someone out there wanting to still revoke an individual proxy, while letting hundreds of others live.

Oh... This is definitely reasonable. So the correct choice is: accept it on both `Proxy.revocable` and `new Proxy` (as 3rd argument)

2022-04-08 03:31 UTC, ajvincent commented
> The current semantics allows the engine to GC all targets & handlers of the proxy.
> 
> > I think having Proxy.revocable() not always return {proxy, revoke} is something we can not ask for.
> 
> What about changing `Proxy.revocable` to return `{ proxy: T, revoke?: Function }`? I prefer adding this functionality to the `Proxy.revocable` instead of `new Proxy` because it has better semantics.

This proposal is definitely aiming at `Proxy.revocable`, and considering `new Proxy` in #6.

2022-04-09 11:38 UTC, Jack-Works commented
spec updated.

2022-04-09 17:29 UTC, ajvincent approved these changes
You've answered my objection.  I'll wait for the others to review before merging, for now.

2022-04-10 00:23 UTC, ajvincent commented
I still have a concern about directly referencing AbortController as the mass-revocation signal basis.

2022-04-10 03:14 UTC, Jack-Works commented
Maybe we can follow https://github.com/tc39/proposal-cancellation/issues/31 as our foundation.

2022-07-13 17:14 UTC, ajvincent commented
There's a conflict.  Can you please update this PR to account for that?

2022-07-14 03:45 UTC, Jack-Works commented
@ajvincent done

2022-07-14 04:07 UTC, ajvincent commented on index.html
> +    <emu-alg><ol><li>Let <var>p</var> be ?&nbsp;<emu-xref aoid="ProxyCreate"><a href="https://tc39.es/ecma262/#sec-proxycreate">ProxyCreate</a></emu-xref>(<var>target</var>, <var>handler</var>).</li>
I'm not sure if you updated the spec text so step 4h, which sets the `[[RevocationSignal]]` to null despite step 3a.  

I'll bet it's standard for the spec editing code to put all of this on one line, but it's really hard on the eyes to have to scroll so far in to fix a bug on one line.

I will merge with this bug in, and I ask you to write a follow-up PR to fix the bug.

Per #6, I'd also like a follow-up to modify `new Proxy()` as well.

2022-07-14 04:08 UTC, ajvincent commented on index.html
> +    <emu-alg><ol><li>Let <var>p</var> be ?&nbsp;<emu-xref aoid="ProxyCreate"><a href="https://tc39.es/ecma262/#sec-proxycreate">ProxyCreate</a></emu-xref>(<var>target</var>, <var>handler</var>).</li>
Ah, I see it's generated from spec.emu below.  I didn't know that.

2022-07-14 04:09 UTC, ajvincent approved these changes

2022-07-14 04:09 UTC, merged